### ISSUE TITLE
大写字母开头的单词无法用数字键上屏候选项

### ISSUE THREAD

**Issue by boomker** [tumuyan/rime-melt#11]
<img width="131" alt="image" src="https://user-images.githubusercontent.com/19751472/228578014-f7ebe69d-379f-4137-a141-4eb61382ce27.png">

如上图， 数字被当作输入码了。怎么解决这个问题，谢谢

**Comment by abcdefg233** [comment]
发送build文件供我们一探究竟！？

**Comment by tumuyan** [comment]
rime本身不能区分小键盘和字母区的数字键，本方案用lua做了区分，字母区的数字键可以选字（除非你没有按照说明引入lua）。

**Comment by boomker** [comment]
> rime本身不能区分小键盘和字母区的数字键，本方案用lua做了区分，字母区的数字键可以选字（除非你没有按照说明引入lua）。

我的情况刚好相反，小键盘区的数字键可以选择对应候选项上屏（仅在英文字母大写开头）， 输入汉字和小写英文单词可以正常用字母区的数字上屏候选
