### ISSUE TITLE
long_word_filter代码是不是写错了？

### ISSUE THREAD

**Issue by xjkdev** [tumuyan/rime-melt#12]
这里是不是应该是`#l`？
我不是很懂lua，但`#table`取的是table这个全局对象的长度吧？
如果我搞错了，很抱歉占用你的时间。

https://github.com/tumuyan/rime-melt/blob/96c1033ecb5cad739db9b933496b0fcfe8520820/lua/melt.lua#L155

**Comment by boomker** [comment]
> 这里是不是应该是`#l`？ 我不是很懂lua，但`#table`取的是table这个全局对象的长度吧？ 如果我搞错了，很抱歉占用你的时间。
> 
> https://github.com/tumuyan/rime-melt/blob/96c1033ecb5cad739db9b933496b0fcfe8520820/lua/melt.lua#L155

我对这个也很疑惑， 搞不明白要有这句判断逻辑

**Comment by xjkdev** [comment]
@tumuyan 能否来看一下？

**Comment by tumuyan** [comment]
我也忘了是怎么回事了，很可能写错了。
@boomker   从逻辑上讲应该是处理一定数量的候选后不再处理， 已经按照这个思路做了修复
